const { withPodfile } = require('@expo/config-plugins');

const MARKER = '# @generated by with-ios-podfile-fixes';

// The GoogleSignIn SDK (via ExpoAdapterGoogleSignIn) pulls in AppCheckCore,
// whose transitive deps (GoogleUtilities, RecaptchaInterop) do not define
// modules, so CocoaPods aborts static-library integration without modular
// headers. Declaring them here merges the :modular_headers attribute into the
// resolved pods without pinning versions. iOS-only (Podfile); Android build
// untouched.
// TODO: revisit if Google Drive backup is ever configured for iOS (needs
// GoogleService-Info.plist + URL scheme) and the dependency chain changes.
const MODULAR_HEADERS_SNIPPET = `${MARKER}
  pod 'GoogleUtilities', :modular_headers => true
  pod 'RecaptchaInterop', :modular_headers => true`;

const withIosPodfileFixes = config => {
  config = withPodfile(config, config => {
    // NOTE: the podfile base mod provides modResults as a FileInfo object
    // ({ path, contents }), not a raw string.
    const contents = config.modResults.contents ?? '';
    if (!contents.includes(MARKER)) {
      config.modResults.contents = contents.replace(
        '  use_expo_modules!\n',
        `  use_expo_modules!\n${MODULAR_HEADERS_SNIPPET}\n`,
      );
    }
    return config;
  });

  return config;
};

module.exports = withIosPodfileFixes;
